
#SCRIPT D'INSTALLATION DDCLIENT POUR UN DYNDNS OVH

#!/bin/bash

if (whiptail --title "Installation de DDCLIENT" --yesno "Voulez-vous installer DDClient pour un DynDNS OVH ?" 8 78) then
    	whiptail --title "Message d'informations" --msgbox "Veuillez laisser les champs à vide et sélectionner les premiers champs à chaque question." 8 78
	sudo apt-get install ddclient

	#PARTIE variable pour le fichier ddclient.conf
	login=$(whiptail --inputbox "Quel est votre login créée dans OVH pour votre DynDNS ?" 8 78 --title "Login DynDNS OVH" 3>&1 1>&2 2>&3)

	password=$(whiptail --passwordbox "Quel est votre mot de passe de votre DynDNS ?" 8 78 --title "MDP DynDNS OVH" 3>&1 1>&2 2>&3)

	sousDomaine=$(whiptail --inputbox "Quel est votre sous-domaine OVH ?" 8 78 --title "Domaine DynDNS OVH" 3>&1 1>&2 2>&3)

	#PARTIE DU FICHIER ddclient.conf
	sudo rm /etc/ddclient.conf
	sudo touch /etc/ddclient.conf
	sudo 777 /etc/ddclient.conf
	echo "# Configuration file for ddclient generated by debconf" > '/etc/ddclient.conf'
	echo "#" >> '/etc/ddclient.conf'
	echo "# /etc/ddclient.conf" >> '/etc/ddclient.conf'
	echo "" >> '/etc/ddclient.conf'
	echo "protocol=dyndns2" >> '/etc/ddclient.conf'
	echo "use=web, web=checkip.dyndns.com" >> '/etc/ddclient.conf'
	echo "serveur=www.ovh.com" >> '/etc/ddclient.conf'
	echo "login="$login >> '/etc/ddclient.conf'
	echo "password="$password >> '/etc/ddclient.conf'
	echo $sousDomaine >> '/etc/ddclient.conf'

	whiptail --title "Message d'informations" --msgbox "Installation et configuration effectuée avec succés." 8 78
else
    exit
fi

